### ISSUE TITLE
What's the difference between getBoundingClientRect?

### ISSUE THREAD

**Issue by futurist** [kyungw00k/element-client-rect#1]
See [getBoundingClientRect](https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect), what's the difference?

**Comment by kyungw00k** [comment]
This module is a ponyfill of `getBoundingClientRect`, which means, it doesn't need to use this module if you are only care about concern only in `Modern browser`.

Basically, it aims to work as same as  [getBoundingClientRect](https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect).
